#!/usr/bin/env python3
"""Add OAuth 2.1 authentication and per-tool roles to an existing MCP server
project generated by the mcp-server-scaffold skill.

The mechanical half is automated here: the token verifier, the Keycloak realm,
the full-stack auth test, the container wiring. What is left for a person or a
model is the half that needs judgment — which role each tool requires.

    python add_auth.py --dir ./file-tools

Existing files are backed up to <name>.pre-auth before being replaced. Run with
--dry-run first if you want to see the plan without touching anything.
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    yaml = None

ASSETS = Path(__file__).resolve().parent.parent / "assets"

# Files the scaffold always produces. Their absence means this is not a
# scaffolded project, and patching blindly would make a mess.
REQUIRED = ("http_server.py", "test_server.py", "Dockerfile", "docker-compose.yaml")


def die(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(1)


def render(template: str, subs: dict[str, str]) -> str:
    text = (ASSETS / template).read_text(encoding="utf-8")
    for k, v in subs.items():
        text = text.replace("{{" + k + "}}", v)
    left = re.findall(r"\{\{[A-Z_]+\}\}", text)
    if left:
        die(f"{template}: unsubstituted placeholders {sorted(set(left))}")
    return text


def find_server_module(root: Path) -> str:
    """The scaffold's http_server.py imports the server module by name."""
    m = re.search(r"^from\s+(\w+)\s+import\s+mcp",
                  (root / "http_server.py").read_text(encoding="utf-8"), re.M)
    if not m:
        die("could not find the server module name in http_server.py — is this a scaffolded project?")
    return m.group(1)


def find_port(root: Path) -> str:
    text = (root / "Dockerfile").read_text(encoding="utf-8")
    m = re.search(r"^\s*PORT=(\d+)", text, re.M) or re.search(r"^EXPOSE\s+(\d+)", text, re.M)
    return m.group(1) if m else "8000"


def find_image_name(root: Path) -> str:
    m = re.search(r"^\s*image:\s*([\w.\-/]+):latest",
                  (root / "docker-compose.yaml").read_text(encoding="utf-8"), re.M)
    return m.group(1) if m else "mcp-server"


def backup(path: Path, dry: bool) -> None:
    if path.exists():
        dest = path.with_suffix(path.suffix + ".pre-auth")
        print(f"  backup {path.name} -> {dest.name}")
        if not dry:
            shutil.copy2(path, dest)


def service_block(lines: list[str], name: str) -> tuple[int, int] | None:
    """Line range of one compose service, from its header to the next one."""
    start = next((i for i, l in enumerate(lines) if l.rstrip() == f"  {name}:"), None)
    if start is None:
        return None
    for j in range(start + 1, len(lines)):
        if re.match(r"^  \S", lines[j]) or re.match(r"^\S", lines[j]):
            return start, j
    return start, len(lines)


def patch_compose(root: Path, subs: dict[str, str], dry: bool) -> bool:
    """Insert the auth env vars and append the keycloak/test-auth services.

    Text insertion rather than parse-and-re-emit, because a YAML round trip
    would strip every comment in the file. The result is validated as YAML
    before it is written, and the whole thing is skipped — with a snippet
    written out for a human to merge — if the file does not have the shape the
    scaffold produces.
    """
    path = root / "docker-compose.yaml"
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)

    if service_block(lines, "mcp-server") is None:
        return False

    def insert_env(buf: list[str], service: str, template: str) -> list[str]:
        """Add env vars to a service, creating the environment block if absent."""
        sp = service_block(buf, service)
        if sp is None:
            return buf
        s, e = sp
        env = render(template, subs).splitlines(keepends=True)
        idx = next((i for i in range(s, e) if buf[i].rstrip() == "    environment:"), None)
        if idx is None:
            return buf[:s + 1] + ["    environment:\n"] + env + buf[s + 1:]
        return buf[:idx + 1] + env + buf[idx + 1:]

    new = insert_env(lines, "mcp-server", "compose-env.yaml.tmpl")
    # The in-process test imports the server module, which now builds
    # AuthSettings at import time and so needs an issuer string present even
    # though it never contacts one.
    new = insert_env(new, "test", "compose-env-test.yaml.tmpl")

    text = "".join(new).rstrip() + "\n" + render("compose-services.yaml.tmpl", subs)
    if yaml is not None:
        try:
            parsed = yaml.safe_load(text)
        except yaml.YAMLError as exc:
            die(f"the patched docker-compose.yaml is not valid YAML: {exc}")
        for expected in ("keycloak", "test-auth", "mcp-server"):
            if expected not in parsed.get("services", {}):
                die(f"the patched docker-compose.yaml lost the {expected!r} service")
    backup(path, dry)
    print("  patch  docker-compose.yaml (auth env on mcp-server, + keycloak and test-auth)")
    if not dry:
        path.write_text(text, encoding="utf-8")
    return True


def patch_requirements(root: Path, dry: bool) -> None:
    path = root / "requirements.txt"
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    if re.search(r"^\s*PyJWT", text, re.M | re.I):
        print("  skip   requirements.txt (PyJWT already listed)")
        return
    # PyJWT arrives as a transitive dependency of mcp today, but relying on
    # that would break the day mcp drops it. The cryptography extra is what
    # supplies RS256 verification.
    addition = 'PyJWT[crypto]>=2.10   # RS256 verification of the issuer\'s tokens\n'
    print("  patch  requirements.txt (+ PyJWT[crypto])")
    if not dry:
        path.write_text(text.rstrip() + "\n" + addition, encoding="utf-8")


def patch_dockerfile(root: Path, dry: bool) -> None:
    path = root / "Dockerfile"
    text = path.read_text(encoding="utf-8")
    if "auth.py" in text:
        print("  skip   Dockerfile (auth.py already copied)")
        return
    m = re.search(r"^COPY .*test_server\.py.*$", text, re.M)
    if not m:
        die("could not find the COPY line naming test_server.py in the Dockerfile")
    line = m.group(0)
    new_line = line + "\nCOPY auth.py test_auth.py ./"
    backup(path, dry)
    print("  patch  Dockerfile (+ COPY auth.py test_auth.py)")
    if not dry:
        path.write_text(text.replace(line, new_line), encoding="utf-8")



# The scaffold's README describes a server with no auth, and several of its
# claims become false the moment this script runs — most loudly "There is no
# authentication on that port", which ends up contradicting the auth section we
# append two paragraphs later. These are mechanical edits, so do them here
# rather than leaving them to be noticed later. Anything that does not match is
# reported, not silently skipped.
README_PATCHES = [
    (
        "the file table",
        "| `healthcheck.py` | Container healthcheck; confirms the port is open. |\n"
        "| `test_server.py` | Talks to the server in memory. No network, no subprocess. |",
        "| `auth.py` | Verifies bearer tokens and checks per-tool roles. |\n"
        "| `healthcheck.py` | Container healthcheck; confirms the metadata endpoint answers. |\n"
        "| `test_server.py` | Talks to the server in memory. Checks roles, not tokens. |\n"
        "| `test_auth.py` | Talks to the running server over HTTP with real tokens. |\n"
        "| `keycloak/realm-export.json` | The dev realm: roles, client identities, logins. |\n"
        "| `.env.example` | How to point this at a real OIDC provider. |",
    ),
    (
        "the compose description",
        "| `docker-compose.yaml` | The server and a profile-gated `test` service. |",
        "| `docker-compose.yaml` | The server, Keycloak, and two profile-gated test services. |",
    ),
    (
        "the first-run commands",
        "docker compose run --rm test        # in-process check, no server needed\n"
        "docker compose up                  # serves http://localhost:{{PORT}}/mcp\n"
        "```",
        "docker compose run --rm test            # in-process check, no server needed\n"
        "docker compose --profile dev up -d      # serves http://localhost:{{PORT}}/mcp\n"
        "docker compose run --rm test-auth       # tokens over HTTP, against the running server\n"
        "```\n"
        "\n"
        "The `dev` profile starts Keycloak alongside the server. Without it the server\n"
        "comes up with nowhere to verify tokens against, retries discovery for about\n"
        "thirty seconds, and exits. Use a plain `docker compose up` only once\n"
        "`OIDC_ISSUER` in `.env` points at a real provider.",
    ),
    (
        "the stdio section",
        "stdio is the default transport, which is why this needs no `--transport` flag.",
        "stdio is the default transport, which is why this needs no `--transport` flag.\n"
        "\n"
        "**This route no longer works now that the server has auth, and that is not a\n"
        "configuration problem.** Tokens are verified by HTTP middleware, and stdio has\n"
        "no HTTP layer to carry an `Authorization` header, so nothing ever sets a caller\n"
        "identity. The tools still list, and every call comes back with the tool's role\n"
        "check refusing an unauthenticated caller. The module also builds its auth\n"
        "settings at import, so `OIDC_ISSUER` has to be set for it to start at all.\n"
        "Use the HTTP route above.",
    ),
    (
        "the open-port note",
        "There is no authentication on that port. That is fine on localhost and not fine\n"
        "on a public interface; put it behind OAuth 2.1 before exposing it.",
        "The port is authenticated: anything without a valid bearer token gets an HTTP\n"
        "401 during the handshake, before a tool is reachable. What is still\n"
        "development-grade is everything around it — Keycloak runs over plain HTTP with\n"
        "a fixed admin password, the token audience is unchecked, and the dev\n"
        "credentials are committed to this repository. See [What is deliberately not\n"
        "covered](#what-is-deliberately-not-covered).",
    ),
(
        "the HTTP registration command",
        "With `docker compose up` running, register the URL with Claude Code:\n"
        "\n"
        "```bash\n"
        "claude mcp add --transport http {{README_SLUG}} http://localhost:{{PORT}}/mcp\n"
        "```",
        "The server requires a token, so a bare URL no longer connects — it gets an\n"
        "HTTP 401. Do not paste a token in as a header either: an access token lasts\n"
        "five minutes and a pasted one cannot renew itself, and a host that sees an\n"
        "`Authorization` header stops there rather than signing in. Sign in instead,\n"
        "and the host renews the token on its own.\n"
        "\n"
        "```bash\n"
        "docker compose --profile dev up -d\n"
        "\n"
        "claude mcp add --transport http --scope user \\\n"
        "  --client-id {{CLIENT_OAUTH}} --callback-port {{CALLBACK_PORT}} \\\n"
        "  {{README_SLUG}} http://localhost:{{PORT}}/mcp\n"
        "\n"
        "claude mcp login {{README_SLUG}}\n"
        "```\n"
        "\n"
        "Sign in as `{{USER_WRITER}}` (password `{{PASSWORD_WRITER}}`) for a connection\n"
        "that may write, or `{{USER_READER}}` (`{{PASSWORD_READER}}`) for a read-only\n"
        "one. `--client-id` is required: without it the host attempts Dynamic Client\n"
        "Registration, which Keycloak refuses. See [Staying connected: refresh\n"
        "tokens](#staying-connected-refresh-tokens) for the details.",
    ),
    (
        "the quick-reference rows",
        "| Serve over HTTP | `docker compose up` |",
        "| Serve over HTTP | `docker compose --profile dev up -d` (server + local issuer) |\n"
        "| Test the auth boundary | `docker compose run --rm test-auth` |",
    ),
    (
        "the quick-reference registration row",
        "| Register with Claude Code | `claude mcp add --transport http {{README_SLUG}} http://localhost:{{PORT}}/mcp` |",
        "| Register with Claude Code | `claude mcp add --transport http --client-id {{CLIENT_OAUTH}} --callback-port {{CALLBACK_PORT}} {{README_SLUG}} http://localhost:{{PORT}}/mcp` |\n"
        "| Sign in | `claude mcp login {{README_SLUG}}` |",
    ),
]


def patch_readme(root, subs, dry_run):
    """Correct the scaffold README's pre-auth claims. Reports what it could not find."""
    path = root / "README.md"
    if not path.exists():
        print("  skip   README.md (not found) — write the auth section in by hand")
        return
    text = path.read_text(encoding="utf-8")
    applied, missed = [], []
    for label, old, new in README_PATCHES:
        for k, v in subs.items():
            old = old.replace("{{" + k + "}}", v)
            new = new.replace("{{" + k + "}}", v)
        if old in text:
            text = text.replace(old, new, 1)
            applied.append(label)
        else:
            missed.append(label)
    if not dry_run and applied:
        path.write_text(text, encoding="utf-8")
    print(f"  patch  README.md ({len(applied)} of {len(README_PATCHES)} pre-auth claims corrected)")
    for label in missed:
        print(f"         COULD NOT FIND {label} — check README.md says the port is "
              f"authenticated and that first-run uses --profile dev")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--dir", required=True, help="The scaffolded project to add auth to.")
    p.add_argument("--realm", help="Keycloak realm name. Default: the image name.")
    p.add_argument("--role-read", default="tools:read", help="Role for read-only tools.")
    p.add_argument("--role-write", default="tools:write", help="Role for state-changing tools.")
    p.add_argument("--keycloak-port", default="8080", help="Host port for Keycloak (default: 8080).")
    p.add_argument("--dry-run", action="store_true", help="Print the plan, change nothing.")
    p.add_argument("--callback-port", type=int, default=8123,
                   help="Port the MCP host listens on for the OAuth callback (default: 8123). "
                        "Registered as a redirect URI in the realm; pass the same value to "
                        "`claude mcp add --callback-port`.")
    p.add_argument("--force", action="store_true", help="Proceed even if auth.py already exists.")
    args = p.parse_args()

    root = Path(args.dir).resolve()
    if not root.is_dir():
        die(f"{root} is not a directory")
    missing = [f for f in REQUIRED if not (root / f).exists()]
    if missing:
        die(f"{root.name} does not look like a scaffolded MCP project — missing {missing}. "
            f"Generate one with the mcp-server-scaffold skill first.")
    if (root / "auth.py").exists() and not args.force:
        die("auth.py already exists — this project already has auth. "
            "Add a tool's role check by hand, or pass --force to regenerate the auth files.")

    module = find_server_module(root)
    port = find_port(root)
    image = find_image_name(root)
    realm = args.realm or image
    subs = {
        "SERVER_NAME": module.replace("_server", "").replace("_", " ").title().replace(" ", ""),
        "MODULE": module,
        "PORT": port,
        "IMAGE_NAME": image,
        "SERVER_SLUG": image,
        # What the scaffold README calls the server in `claude mcp add`. It is
        # the image name without the mcp- prefix, not the image name itself.
        "README_SLUG": image[4:] if image.startswith("mcp-") else image,
        "REALM": realm,
        "ROLE_READ": args.role_read,
        "ROLE_WRITE": args.role_write,
        "KEYCLOAK_PORT": str(args.keycloak_port),
        "CLIENT_READER": "agent-reader",
        "CLIENT_WRITER": "agent-writer",
        "SECRET_READER": "reader-dev-secret",
        "SECRET_WRITER": "writer-dev-secret",
        # The interactive identity an MCP host signs in through. Separate from
        # the two machine clients because it is public (no secret, PKCE
        # instead) and because it is the only one that issues refresh tokens.
        "CLIENT_OAUTH": "claude-code",
        "CALLBACK_PORT": str(args.callback_port),
        "USER_READER": "dev-reader",
        "USER_WRITER": "dev-writer",
        "PASSWORD_READER": "dev-reader-password",
        "PASSWORD_WRITER": "dev-writer-password",
    }

    print(f"Project: {root}")
    print(f"  server module: {module}.py   port: {port}   image: {image}   realm: {realm}")
    print(f"  roles: {args.role_read} (read), {args.role_write} (write)")
    print()

    new_files = {
        "auth.py": "auth.py.tmpl",
        "test_auth.py": "test_auth.py.tmpl",
        "healthcheck.py": "healthcheck.py.tmpl",
        ".env.example": "env.example.tmpl",
        "keycloak/realm-export.json": "realm-export.json.tmpl",
    }
    for name, tmpl in new_files.items():
        target = root / name
        if target.exists():
            backup(target, args.dry_run)
        print(f"  write  {name}")
        if not args.dry_run:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(render(tmpl, subs), encoding="utf-8")

    patch_requirements(root, args.dry_run)
    patch_dockerfile(root, args.dry_run)
    merged = patch_compose(root, subs, args.dry_run)
    if not merged:
        snippet = root / "docker-compose.auth-snippet.yaml"
        print(f"  WRITE  {snippet.name} — could not find an 'mcp-server' service to patch, "
              f"so the additions were written here for you to merge by hand")
        if not args.dry_run:
            snippet.write_text(render("compose-env.yaml.tmpl", subs)
                               + render("compose-services.yaml.tmpl", subs), encoding="utf-8")

    patch_readme(root, subs, args.dry_run)

    # Reference copies, for the model or person doing the remaining edits.
    for name, tmpl in (("test_server_identity_snippet.py", "test_server_identity_snippet.py.tmpl"),
                       ("README-auth-section.md", "README-auth.md.tmpl")):
        print(f"  write  {name} (reference — delete once you have used it)")
        if not args.dry_run:
            (root / name).write_text(render(tmpl, subs), encoding="utf-8")

    print(f"""
Still to do by hand — these need judgment, not templating:

  1. {module}.py — wire the verifier in:
         from auth import JWKSTokenVerifier, auth_settings, require_role
         mcp = MCPServer(..., token_verifier=JWKSTokenVerifier(), auth=auth_settings())
     then add require_role("{args.role_read}") or require_role("{args.role_write}")
     as the first line of every tool, and say so in the instructions string.

  2. test_server.py — the in-process test has no identity now, so every guarded
     tool would fail. Fold in test_server_identity_snippet.py.

  3. test_auth.py — fill in EXPECTATIONS with one row per tool.

  4. README.md — append README-auth-section.md and fill in its role table. The
     pre-auth claims elsewhere in it were corrected above; check the report for
     any the patcher could not find.

Then: docker compose --profile dev up -d --build
      docker compose run --rm test                     # roles, in-process
      docker compose run --rm test-auth                 # tokens, over HTTP
""")
    if args.dry_run:
        print("(dry run — nothing was written)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
